Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/cli/run.py", line 929, in build_workflow
    retval["workflow"] = init_xcpd_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/base.py", line 164, in init_xcpd_wf
    single_subj_wf = init_subject_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/base.py", line 313, in init_subject_wf
    layout, subj_data = collect_data(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/utils/bids.py", line 266, in collect_data
    raise FileNotFoundError(f"No {field} found with query: {queries[field]}")
FileNotFoundError: No t1w found with query: {'datatype': 'anat', 'space': None, 'suffix': 'T1w', 'extension': '.nii.gz'}
